name: timezone
version: 0.7.0-nullsafety.0
description: Time zone database and time zone aware DateTime.
repository: https://github.com/srawlins/timezone
environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies:
  path: ^1.8.0-nullsafety.3
dev_dependencies:
  args: any
  file: ^6.0.0-nullsafety
  glob: ^2.0.0-nullsafety
  logging: any
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13

dependency_overrides:
  glob:
    git: https://github.com/dart-lang/glob.git
