name: timezone
version: 0.7.1
description: Time zone database and time zone aware DateTime.
repository: https://github.com/srawlins/timezone
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.0
dev_dependencies:
  args: any
  file: ^6.1.2
  glob: ^2.0.1
  lints: ^1.0.1
  logging: any
  test: ^1.17.11

